name = "stround-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables that need to be set in Cloudflare Workers
# Set these in the Cloudflare dashboard or using wrangler secret put
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY  
# SUPABASE_ANON_KEY
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET

[env.production]
vars = { 
  ENVIRONMENT = "production",
  API_BASE_URL = "https://stround-api.your-domain.workers.dev",
  CLIENT_URL = "https://your-app-domain.com"
}

[env.development]
vars = { 
  ENVIRONMENT = "development",
  API_BASE_URL = "http://localhost:8787",
  CLIENT_URL = "http://localhost:8081"
}
