name = "stround-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables that need to be set in Cloudflare Workers
# Set these in the Cloudflare dashboard or using wrangler secret put
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY  
# SUPABASE_ANON_KEY
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]  
vars = { ENVIRONMENT = "development" }